# Site Info
title:              "Wei's Notes"
logo_url:           "/assets/images/wei.jpg"
description:        "一箪食，一瓢饮，在陋巷"

# Author Info
author_name:        "Wei Jingyu"
author_email:       wei@weijingyu.com

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /note/:year/:title # Post permalink
timezone:           Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to false to disable
# ba_track_id:        14b683def2184e3a3cd772efac8770cc
google_analytics:   UA-87353108-1

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
